export { Companion } from './components/Companion'
export { CompanionSprite } from './components/CompanionSprite'
export { CompanionPetPicker } from './components/CompanionPetPicker'
export { useCompanionStore, useTeacherName, currentTeacherName } from './store/companion-store'
export { COMPANION_PETS, getCompanionPet } from './lib/sprite'
export { spriteFrames, COMPANION_STATES } from './types'
export type { CompanionAiState } from './types'
export type { CompanionPetId } from './lib/sprite'
