"""create learning_sessions learning_events book_progress

Revision ID: 52cd66eb864b
Revises: b6e5c24af284
Create Date: 2026-08-19 15:54:43.688705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52cd66eb864b'
down_revision: Union[str, Sequence[str], None] = 'b6e5c24af284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('entry_route', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','ENDED','ABANDONED')", name='ck_learning_sessions_status'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_learning_sessions_duration'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_learning_sessions_ended_after_started'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_learning_sessions_student_started', 'learning_sessions', ['student_id', 'started_at'], unique=False)
    op.create_index('uq_learning_sessions_one_active', 'learning_sessions', ['student_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('book_progress',
    sa.Column('progress_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'NOT_STARTED'"), nullable=False),
    sa.Column('position_percent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED','READING','COMPLETED')", name='ck_book_progress_status'),
    sa.CheckConstraint('position_percent BETWEEN 0 AND 100', name='ck_book_progress_position'),
    sa.CheckConstraint('total_seconds >= 0', name='ck_book_progress_total_seconds'),
    sa.ForeignKeyConstraint(['block_id'], ['content_blocks.block_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('student_id', 'book_id', name='uq_book_progress_student_book')
    )
    op.create_table('learning_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_point_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    # FK→conversations 延迟到 Phase 4 补（0-E 已裁定）
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    # FK→quiz_sessions 延迟到 Phase 6 补（0-E 已裁定）
    sa.Column('quiz_session_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('CHAPTER_STARTED','CHAPTER_FINISHED','SECTION_READ','KNOWLEDGE_CARD_VIEWED','HELP_REQUESTED','EXPLAIN_REQUESTED','SUMMARY_REQUESTED','QUIZ_CREATED','QUIZ_ANSWERED','ANSWER_CORRECT','ANSWER_WRONG','HINT_REQUESTED','QUESTION_ASKED','BOOK_STARTED','BOOK_FINISHED','VOICE_SESSION_STARTED','ROLE_SWITCHED','TEXT_SELECTED')", name='ck_learning_events_type'),
    sa.ForeignKeyConstraint(['block_id'], ['content_blocks.block_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.session_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_learning_events_session', 'learning_events', ['session_id'], unique=False)
    op.create_index('ix_learning_events_student_occurred', 'learning_events', ['student_id', 'occurred_at'], unique=False)
    op.create_index('ix_learning_events_student_type', 'learning_events', ['student_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_events_student_type', table_name='learning_events')
    op.drop_index('ix_learning_events_student_occurred', table_name='learning_events')
    op.drop_index('ix_learning_events_session', table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_table('book_progress')
    op.drop_index('uq_learning_sessions_one_active', table_name='learning_sessions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_learning_sessions_student_started', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    # ### end Alembic commands ###
