"""create users student_profiles student_preferences

Revision ID: 8468855342d3
Revises: 
Create Date: 2026-08-19 15:16:38.464499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8468855342d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','DISABLED')", name='ck_users_status'),
    sa.CheckConstraint("user_type IN ('STUDENT','ADMIN')", name='ck_users_user_type'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_users_phone', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_table('student_profiles',
    sa.Column('student_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=16), server_default=sa.text("'zh-CN'"), nullable=False),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    # FK→teacher_roles 延迟到 Phase 11 补（0-E 已裁定：本列先建，不加 FK 约束）
    sa.Column('current_teacher_role_id', sa.UUID(), nullable=True),
    sa.Column('learning_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_learning_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_books', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_chapters', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quiz_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_books >= 0', name='ck_student_profiles_completed_books'),
    sa.CheckConstraint('completed_chapters >= 0', name='ck_student_profiles_completed_chapters'),
    sa.CheckConstraint('grade BETWEEN 1 AND 12', name='ck_student_profiles_grade'),
    sa.CheckConstraint('learning_days >= 0', name='ck_student_profiles_learning_days'),
    sa.CheckConstraint('quiz_count >= 0', name='ck_student_profiles_quiz_count'),
    sa.CheckConstraint('total_learning_minutes >= 0', name='ck_student_profiles_total_minutes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_preferences',
    sa.Column('preference_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('preferred_explanation_style', sa.String(length=32), nullable=False),
    sa.Column('preferred_difficulty', sa.String(length=16), nullable=False),
    sa.Column('preferred_session_length', sa.String(length=16), nullable=False),
    sa.Column('voice_preference', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('active_questioning_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('daily_learning_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("preferred_difficulty IN ('EASY','MEDIUM','HARD')", name='ck_student_preferences_difficulty'),
    sa.CheckConstraint("preferred_explanation_style IN ('EXAMPLE_BASED','VISUAL','STORY','DIRECT_DEFINITION','STEP_BY_STEP','CODE','INTERACTIVE')", name='ck_student_preferences_explanation_style'),
    sa.CheckConstraint("preferred_session_length IN ('SHORT','MEDIUM','LONG')", name='ck_student_preferences_session_length'),
    sa.CheckConstraint('daily_learning_minutes >= 0', name='ck_student_preferences_daily_minutes'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_preferences')
    op.drop_table('student_profiles')
    op.drop_index('uq_users_phone', table_name='users', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('uq_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
