"""create books chapters content_blocks knowledge_points

Revision ID: b6e5c24af284
Revises: 8468855342d3
Create Date: 2026-08-19 15:50:19.711586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6e5c24af284'
down_revision: Union[str, Sequence[str], None] = '8468855342d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade_min', sa.Integer(), nullable=False),
    sa.Column('grade_max', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('copyright_status', sa.String(length=128), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'DRAFT'"), nullable=False),
    # FK→admins 延迟到 Phase 10 补（0-E 已裁定：本列先建，不加 FK 约束）
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('EASY','MEDIUM','HARD')", name='ck_books_difficulty'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_books_status'),
    sa.CheckConstraint('estimated_minutes > 0', name='ck_books_estimated_minutes'),
    sa.CheckConstraint('grade_max BETWEEN 1 AND 12', name='ck_books_grade_max'),
    sa.CheckConstraint('grade_min <= grade_max', name='ck_books_grade_range'),
    sa.CheckConstraint('grade_min BETWEEN 1 AND 12', name='ck_books_grade_min'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index('ix_books_grade_min_max', 'books', ['grade_min', 'grade_max'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('knowledge_point_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')", name='ck_knowledge_points_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.knowledge_point_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('knowledge_point_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chapters',
    sa.Column('chapter_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter_order', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name='ck_chapters_status'),
    sa.CheckConstraint('estimated_minutes > 0', name='ck_chapters_estimated_minutes'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id'),
    sa.UniqueConstraint('book_id', 'chapter_order', name='uq_chapters_book_order')
    )
    op.create_table('content_blocks',
    sa.Column('block_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=128), nullable=True),
    sa.Column('knowledge_point_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('TITLE','PARAGRAPH','IMAGE','FIGURE','KNOWLEDGE_CARD','EXAMPLE','CALLOUT','HIGHLIGHT')", name='ck_content_blocks_type'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('chapter_id', 'block_order', name='uq_content_blocks_chapter_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_blocks')
    op.drop_table('chapters')
    op.drop_table('knowledge_points')
    op.drop_index('ix_books_grade_min_max', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
